/**
 * Custom admin components, regenerated by `pnpm --filter cms generate:importmap`.
 * Empty until F3 adds the upload table, the tile preview and the publish button.
 */
export const importMap = {};
